<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Product Templates (Seed Data)
    |--------------------------------------------------------------------------
    |
    | This config serves as bootstrap/seed data only.
    | The source of truth is the `product_templates` database table.
    | Templates can be managed from the Admin Panel in the future.
    |
    */

    'templates' => [

        'tshirt' => [
            'name' => 'تيشيرت',
            'name_en' => 'T-Shirt',
            'description' => 'تيشيرت قطن كلاسيكي',
            'display_order' => 1,
            'is_active' => true,
            'slots' => [
                [
                    'slot_key' => 'front_main',
                    'slot_type' => 'main',
                    'name' => 'الواجهة',
                    'view_name' => 'front',
                    'view_index' => 0,
                    'is_required' => true,
                    'display_order' => 1,
                    'default_x' => 50,
                    'default_y' => 80,
                    'default_width' => 400,
                    'default_height' => 350,
                ],
                [
                    'slot_key' => 'back_main',
                    'slot_type' => 'main',
                    'name' => 'الخلف',
                    'view_name' => 'back',
                    'view_index' => 1,
                    'is_required' => true,
                    'display_order' => 2,
                    'default_x' => 50,
                    'default_y' => 80,
                    'default_width' => 400,
                    'default_height' => 350,
                ],
                [
                    'slot_key' => 'left_chest_logo',
                    'slot_type' => 'logo',
                    'name' => 'لوجو الصدر الأيسر',
                    'view_name' => 'front',
                    'view_index' => 0,
                    'is_required' => true,
                    'display_order' => 3,
                    'default_x' => 280,
                    'default_y' => 100,
                    'default_width' => 100,
                    'default_height' => 100,
                ],
                [
                    'slot_key' => 'right_chest_logo',
                    'slot_type' => 'logo',
                    'name' => 'لوجو الصدر الأيمن',
                    'view_name' => 'front',
                    'view_index' => 0,
                    'is_required' => true,
                    'display_order' => 4,
                    'default_x' => 120,
                    'default_y' => 100,
                    'default_width' => 100,
                    'default_height' => 100,
                ],
                [
                    'slot_key' => 'left_sleeve',
                    'slot_type' => 'secondary',
                    'name' => 'الكم الأيسر',
                    'view_name' => 'left_sleeve',
                    'view_index' => 2,
                    'is_required' => false,
                    'display_order' => 5,
                    'default_x' => 100,
                    'default_y' => 100,
                    'default_width' => 150,
                    'default_height' => 200,
                ],
                [
                    'slot_key' => 'right_sleeve',
                    'slot_type' => 'secondary',
                    'name' => 'الكم الأيمن',
                    'view_name' => 'right_sleeve',
                    'view_index' => 3,
                    'is_required' => false,
                    'display_order' => 6,
                    'default_x' => 100,
                    'default_y' => 100,
                    'default_width' => 150,
                    'default_height' => 200,
                ],
            ],
        ],

        'hoodie' => [
            'name' => 'هودي',
            'name_en' => 'Hoodie',
            'description' => 'هودي دافئ مع قبعة',
            'display_order' => 2,
            'is_active' => true,
            'slots' => [
                [
                    'slot_key' => 'front_main',
                    'slot_type' => 'main',
                    'name' => 'الواجهة',
                    'view_name' => 'front',
                    'view_index' => 0,
                    'is_required' => true,
                    'display_order' => 1,
                    'default_x' => 50,
                    'default_y' => 100,
                    'default_width' => 400,
                    'default_height' => 300,
                ],
                [
                    'slot_key' => 'back_main',
                    'slot_type' => 'main',
                    'name' => 'الخلف',
                    'view_name' => 'back',
                    'view_index' => 1,
                    'is_required' => true,
                    'display_order' => 2,
                    'default_x' => 50,
                    'default_y' => 100,
                    'default_width' => 400,
                    'default_height' => 300,
                ],
                [
                    'slot_key' => 'left_chest_logo',
                    'slot_type' => 'logo',
                    'name' => 'لوجو الصدر الأيسر',
                    'view_name' => 'front',
                    'view_index' => 0,
                    'is_required' => true,
                    'display_order' => 3,
                    'default_x' => 280,
                    'default_y' => 120,
                    'default_width' => 100,
                    'default_height' => 100,
                ],
                [
                    'slot_key' => 'right_chest_logo',
                    'slot_type' => 'logo',
                    'name' => 'لوجو الصدر الأيمن',
                    'view_name' => 'front',
                    'view_index' => 0,
                    'is_required' => true,
                    'display_order' => 4,
                    'default_x' => 120,
                    'default_y' => 120,
                    'default_width' => 100,
                    'default_height' => 100,
                ],
                [
                    'slot_key' => 'left_sleeve',
                    'slot_type' => 'secondary',
                    'name' => 'الكم الأيسر',
                    'view_name' => 'left_sleeve',
                    'view_index' => 2,
                    'is_required' => false,
                    'display_order' => 5,
                    'default_x' => 100,
                    'default_y' => 100,
                    'default_width' => 150,
                    'default_height' => 200,
                ],
                [
                    'slot_key' => 'right_sleeve',
                    'slot_type' => 'secondary',
                    'name' => 'الكم الأيمن',
                    'view_name' => 'right_sleeve',
                    'view_index' => 3,
                    'is_required' => false,
                    'display_order' => 6,
                    'default_x' => 100,
                    'default_y' => 100,
                    'default_width' => 150,
                    'default_height' => 200,
                ],
                [
                    'slot_key' => 'pocket',
                    'slot_type' => 'accessory',
                    'name' => 'الجيب',
                    'view_name' => 'front',
                    'view_index' => 0,
                    'is_required' => false,
                    'display_order' => 7,
                    'default_x' => 180,
                    'default_y' => 340,
                    'default_width' => 140,
                    'default_height' => 80,
                ],
                [
                    'slot_key' => 'hood',
                    'slot_type' => 'accessory',
                    'name' => 'القبعة',
                    'view_name' => 'hood',
                    'view_index' => 4,
                    'is_required' => false,
                    'display_order' => 8,
                    'default_x' => 100,
                    'default_y' => 50,
                    'default_width' => 300,
                    'default_height' => 200,
                ],
            ],
        ],

        'polo' => [
            'name' => 'بولو',
            'name_en' => 'Polo',
            'description' => 'قميص بولو كلاسيكي',
            'display_order' => 3,
            'is_active' => true,
            'slots' => [
                [
                    'slot_key' => 'front_main',
                    'slot_type' => 'main',
                    'name' => 'الواجهة',
                    'view_name' => 'front',
                    'view_index' => 0,
                    'is_required' => true,
                    'display_order' => 1,
                    'default_x' => 50,
                    'default_y' => 80,
                    'default_width' => 400,
                    'default_height' => 350,
                ],
                [
                    'slot_key' => 'back_main',
                    'slot_type' => 'main',
                    'name' => 'الخلف',
                    'view_name' => 'back',
                    'view_index' => 1,
                    'is_required' => true,
                    'display_order' => 2,
                    'default_x' => 50,
                    'default_y' => 80,
                    'default_width' => 400,
                    'default_height' => 350,
                ],
                [
                    'slot_key' => 'left_chest_logo',
                    'slot_type' => 'logo',
                    'name' => 'لوجو الصدر الأيسر',
                    'view_name' => 'front',
                    'view_index' => 0,
                    'is_required' => true,
                    'display_order' => 3,
                    'default_x' => 280,
                    'default_y' => 100,
                    'default_width' => 100,
                    'default_height' => 100,
                ],
                [
                    'slot_key' => 'right_chest_logo',
                    'slot_type' => 'logo',
                    'name' => 'لوجو الصدر الأيمن',
                    'view_name' => 'front',
                    'view_index' => 0,
                    'is_required' => true,
                    'display_order' => 4,
                    'default_x' => 120,
                    'default_y' => 100,
                    'default_width' => 100,
                    'default_height' => 100,
                ],
                [
                    'slot_key' => 'left_sleeve',
                    'slot_type' => 'secondary',
                    'name' => 'الكم الأيسر',
                    'view_name' => 'left_sleeve',
                    'view_index' => 2,
                    'is_required' => false,
                    'display_order' => 5,
                    'default_x' => 100,
                    'default_y' => 100,
                    'default_width' => 150,
                    'default_height' => 200,
                ],
                [
                    'slot_key' => 'right_sleeve',
                    'slot_type' => 'secondary',
                    'name' => 'الكم الأيمن',
                    'view_name' => 'right_sleeve',
                    'view_index' => 3,
                    'is_required' => false,
                    'display_order' => 6,
                    'default_x' => 100,
                    'default_y' => 100,
                    'default_width' => 150,
                    'default_height' => 200,
                ],
            ],
        ],

        'sweatshirt' => [
            'name' => 'سويت شيرت',
            'name_en' => 'Sweatshirt',
            'description' => 'سويت شيرت مريح',
            'display_order' => 4,
            'is_active' => true,
            'slots' => [
                [
                    'slot_key' => 'front_main',
                    'slot_type' => 'main',
                    'name' => 'الواجهة',
                    'view_name' => 'front',
                    'view_index' => 0,
                    'is_required' => true,
                    'display_order' => 1,
                    'default_x' => 50,
                    'default_y' => 80,
                    'default_width' => 400,
                    'default_height' => 350,
                ],
                [
                    'slot_key' => 'back_main',
                    'slot_type' => 'main',
                    'name' => 'الخلف',
                    'view_name' => 'back',
                    'view_index' => 1,
                    'is_required' => true,
                    'display_order' => 2,
                    'default_x' => 50,
                    'default_y' => 80,
                    'default_width' => 400,
                    'default_height' => 350,
                ],
                [
                    'slot_key' => 'left_chest_logo',
                    'slot_type' => 'logo',
                    'name' => 'لوجو الصدر الأيسر',
                    'view_name' => 'front',
                    'view_index' => 0,
                    'is_required' => true,
                    'display_order' => 3,
                    'default_x' => 280,
                    'default_y' => 100,
                    'default_width' => 100,
                    'default_height' => 100,
                ],
                [
                    'slot_key' => 'right_chest_logo',
                    'slot_type' => 'logo',
                    'name' => 'لوجو الصدر الأيمن',
                    'view_name' => 'front',
                    'view_index' => 0,
                    'is_required' => true,
                    'display_order' => 4,
                    'default_x' => 120,
                    'default_y' => 100,
                    'default_width' => 100,
                    'default_height' => 100,
                ],
                [
                    'slot_key' => 'left_sleeve',
                    'slot_type' => 'secondary',
                    'name' => 'الكم الأيسر',
                    'view_name' => 'left_sleeve',
                    'view_index' => 2,
                    'is_required' => false,
                    'display_order' => 5,
                    'default_x' => 100,
                    'default_y' => 100,
                    'default_width' => 150,
                    'default_height' => 200,
                ],
                [
                    'slot_key' => 'right_sleeve',
                    'slot_type' => 'secondary',
                    'name' => 'الكم الأيمن',
                    'view_name' => 'right_sleeve',
                    'view_index' => 3,
                    'is_required' => false,
                    'display_order' => 6,
                    'default_x' => 100,
                    'default_y' => 100,
                    'default_width' => 150,
                    'default_height' => 200,
                ],
            ],
        ],

        'custom_empty' => [
            'name' => 'منتج مخصص فارغ',
            'name_en' => 'Custom Empty',
            'description' => 'منتج فارغ — يتم إنشاء المناطق يدوياً',
            'display_order' => 5,
            'is_active' => true,
            'slots' => [],
        ],

    ],

];
